refactor: Make ComponentSet.retrieve() Calls Consistently (#4677)
* fix: set api version consistently when retrieving

* refactor: connection as retrieve option to align

with base/other retrieve operation

* refactor: await for easier debugging

stack is in better order with this change in place

* chore: fix import, add copyright

* refactor: fixup module

* refactor: avoid undefined (reading 'getInstance') err

* test: draft test outline

copied over from integ tests

* test: import and call new fn

TypeError: Cannot read properties of undefined (reading 'getInstance')

* refactor: grab context from elsewhere to

avoid  TypeError: Cannot read properties of undefined

* test: doesnt work TypeError: Cannot read

* test: doesnt work  TypeError: Cannot read

* test: doesnt work  TypeError: Cannot read

* test: doesnt work  TypeError: Cannot read

* test: mock ctxt and utils

* test: get around Message is not a constructor err

* test: mock telem and channel

* feat: export class not instance at res time

* feat: authtinfo

* feat: pers stor

* feat: all the others

* test: get test to run

* test: first legit failing test

* test: passing tests

* refactor: remove unneeded

* test: update unit test

* test: fix integration test to work with new

exported class not instance

* refactor: undo unneeded dev move

* refactor: remove unneeded

* refactor: remove unneeded change

* refactor: put unneeded stuff back

* test: update deploy test

* test: update retrieve test to check for api call

* test: fix failing integ tests

* refactor: remove unneeded

* refactor: remove unneeded