Make orgList use OrgAuthorizations (#4343)
* chore: catch up ra/upgrade_v3_test1 with develop

* chore: fix a lot of soql int tests

* fix: fix sObjectDescribe.test before each

* chore: fix authInfo tests

* chore: remove only and lint fixes

* chore: fix forceAuthAccessTokenLogin test

* chore: ongoing test fixes

* chore: remove onlys

* chore: fix orgList Tests

* chore: fix completion tests

* chore: fix completion tests

* chore: fix chai syntax for authInfo test

* chore: set resource class for circle jobs

* chore: fix circle size config

* chore: play with circle config to see if it improves speed

* chore: remove packaging entry added to package.json

* chore: use keys for default org and dev hub from core v3

* chore: point to the .sfdx root folder, where auth files are located

* chore: use key from core v3

* refactor: correct casing of var name

* refactor: begin working with OrgAuthorization type

* refactor: rework filter fn to use OrgAuthorization

and AuthFields, which is where the fields that were on
"FileInfo" are stored in the core lib

* refactor: remove commented out code that was moved

to be inside the loop and use AuthFields

* refactor: add comments

and remove the one related to state aggregator, since that
is no longer used here

* Revert "chore: use key from core v3"

This reverts commit 2bfc6d2a0c60b6917953314eaca4f015dc94a66c.

* chore: Enable default org to display in status bar and org list to show in Org Picker with core v3 updates (#4290)

* chore: use keys for default org and dev hub from core v3

* chore: point to the .sfdx root folder, where auth files are located

* chore: use key from core v3

* refactor: correct casing of var name

* Revert "chore: use key from core v3"

This reverts commit 2bfc6d2a0c60b6917953314eaca4f015dc94a66c.

* fix: feedback-changes-for-update_v3_test1 (#4302)

* fix: remove unnecessary configs (#4303)

* refactor: get the first failing test to pass

- use the OrgAuthorization data shape in the test
- create a function for getting the AuthFields so that it can be stubbed in the test
- mock the data so that the stubbed scratchAdminUsername is returned in the AuthFields obj
- remove reference to StateAggregator, which is no longer used in the function under test
- next steps: uncomment the remaining tests and make similar fixes

* refactor: update var name

* refactor: make test data structures core types

* chore: remove only

* refactor: remove data that is not used/exercised/expected for the test

a partial org auth object that only contains the data that the test is using is fine here -
accessToken is not needed for these tests

* refactor: add constants to clean up test data and shorten methods

* refactor: move comment to inside of block

* fix: cleanup auth and login from v3 first pass (#4309)

* fix: review cleanup (#4311)

* refactor: get alias from AuthFields and update stub

* refactor: use withArgs instead for more accurate stub

* refactor: stub the alias correctly by putting it in AuthFields

* refactor: go back to orgAuth.aliases for org list

* refactor: fix failing test by fixing data structures

* fix: revert sfdx folder to use .sfdx again

* refactor: revert back to backwards compatible sfdx config for now

with follow up work to use config aggregator and core v3 apis

* refactor: orgUtil commented out temporarily to test build

rolling back some of the changes on the core v3 branch to see a smaller build

* refactor: orgUtil commented out temporarily to test build

rolling back some of the changes on the core v3 branch to see a smaller build

* chore: fix failing test - use sfdx

* chore: rollback chg to fix tests

* chore: rollback to use sfdx and old key

* fix: update for checkForExpiredOrgs() to use OrgAuthorization (#4341)

* fix: update for checkForExpiredOrgs() to use OrgAuthorization

* chore: saved file to run formatter

To get past CircleCI build error:
ERROR: C:/Users/circleci/project/packages/salesforcedx-utils-vscode/src/helpers/utils.ts[26, 1]:
space indentation expected
ERROR: C:/Users/circleci/project/packages/salesforcedx-utils-vscode/src/helpers/utils.ts[28, 1]:
space indentation expected

* fix: moved getAuthFieldsFor() and getDefaultDevHubUsernameorAlias() from orgList to orgUtil

* fix: moved getAuthFieldsFor() and getDefaultDevHubUsernameorAlias() from orgList to orgUtil

* fix: moved getAuthFieldsFor() and getDefaultDevHubUsernameorAlias() from orgList to orgUtil

* fix: converted call to filter() and map() to just a for() loop

* fix: updated asyncFilter() to typed callback

* fix: updated asyncFilter() to typed callback

* fix: updated asyncFilter() to typed callback

Co-authored-by: Kenneth Lewis <kenneth.lewis@salesforce.com>

* chore: fix orgList tests after merge

* chore: clean up

* chore: fixup orgUtil after cherry pick

* chore: remove deprecated type

* chore: update comment

* refactor: use getInstance over create

* test: update forceAuthAccessTokenLogin test for corev3 changes (#4350)

* fix: fixed manifest builder error (#4352)

* refactor: use org api version if no user config (#4348)

* refactor: use org api version if no user config

* refactor: await the setting of the api version

* refactor: first test update

* refactor: update tests and move utility fns

* chore: remove comment

* refactor: fix failing test

No need to call await here

* chore: fix linter issues

* refactor: update tests add expects

* refactor: make fn easy to grok and debug

* refactor: update import and dont notify

if default username is not set

* refactor: get around linter error

Error was: Promises must be handled appropriately

* refactor: use await

* refactor: dont create authInfo if no default usrnm

* refactor: only get api version from org if needed

* refactor: update import

* chore: update to version 55.9.0

* chore: remove unused

* refactor: remove chain operator

getFields always returns an instance of AuthFields

* refactor: use inferred type and check length since

always an array

* refactor: remove catch block

AuthInfo.listAllAuthorizations() will return an empty array if no auths

* refactor: remove test part that stubs filesystem

no longer reading files

* refactor: fix test failure

fails when authFields.scratchAdminUsername is undefined

* refactor: no need to return null

will be an empty array

* refactor: handle possibility of AuthFields being

undefined

* chore: pkg lock

* refactor: var name

* refactor: remove no longer used imports

* refactor: remove unneeded as

* refactor: add return type

* refactor: add return type

* refactor: add return type

* refactor: remove unneeded ?

* refactor: simplify return type, remove conditional

* refactor: use StateAgg to get aliases

to try to get around potential caching issue observed using OrgAuth...

* refactor: use fn on ConfigUtil so stub

can stub service method not internal impl

* refactor: remove unused

* refactor: use clearInstance to get new aliases

when in same process.  (VSCE Uses long running processes)

Co-authored-by: Gordon Bockus <gbockus@salesforce.com>
Co-authored-by: jbeeghly <46358907+jeffb-sfdc@users.noreply.github.com>
Co-authored-by: Ritam Agrawal <72183558+RitamAgrawal@users.noreply.github.com>
Co-authored-by: Randi Wilson <randi274@gmail.com>
Co-authored-by: angela-young <60243824+angela-young@users.noreply.github.com>
Co-authored-by: Ritam Agrawal <ritam.kumari.27@gmail.com>
Co-authored-by: gbockus-sf <76090802+gbockus-sf@users.noreply.github.com>
Co-authored-by: Release Bot <>